# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first terms will be: 1, 2, 3, 5, 8, 13, 21...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibs(max: int):
    a, b = 1, 2
    total = 0
    while b <= max:
        if b % 2 == 0:
            total += b
        a, b = b, a + b
    return total


if __name__ == '__main__':
    print(even_fibs(4000000))
